In [11]:
import pandas as pd
filename = './CutFrame_Output/output0/use0.txt'
def remove_brackets(line):
    print(line.strip('['))

def replace_last_row_with_zeros(filename):
    # 读取文件
    with open(filename, 'r') as file:
        lines = file.readlines()
    
    # 删除每行两边的括号
    cleaned_lines = [remove_brackets(line) for line in lines]
    
    # 将数据转换为DataFrame
    data = pd.DataFrame([list(map(float, line.split())) for line in cleaned_lines])
    
    # 替换最后一行的值为0
    data.iloc[-1] = 0
    
    # 写回文件
    data.to_csv(filename, sep=' ', header=False, index=False, float_format='%.6f')

In [12]:
replace_last_row_with_zeros(filename)

 [8.28000000e+02 6.35000000e+02 6.98538959e-01 3.00000000e+00]

 [9.18000000e+02 5.12000000e+02 9.33560193e-01 4.00000000e+00]

 [6.12000000e+02 1.02500000e+03 8.84738743e-01 1.00000000e+01]

 [7.93000000e+02 5.70000000e+02 8.98546219e-01 1.00000000e+00]



AttributeError: 'NoneType' object has no attribute 'split'

In [19]:
import numpy as np

def replace_last_line_with_zeros(file_path):
    # 读取文件中的所有数据
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # 将最后一行替换为零
    if lines:
        # last_line = np.zeros_like(np.fromstring(lines[-1], sep=' '))
        last_line = np.array([[0, 0, 0, 0]])
        lines[-1] = ' '.join(map(str, last_line)) + '\n'

    # 将数据写回文件
    with open(file_path, 'w') as file:
        file.writelines(lines)

# 示例文件路径
file_path = filename
replace_last_line_with_zeros(file_path)


In [20]:
from utils import process_data
process_data(file_path)

[[828.0, 635.0], [918.0, 512.0], [612.0, 1025.0], [0.0, 0.0]]

In [1]:
from utils import replace_data
replace_data('CutFrame_Output')

[]